site_name: Tax Practice Management System
site_description: A comprehensive tax practice management solution
site_author: Ambitious Concepts

# Repository information
repo_url: https://github.com/ambitiousconcepts/TaxDocs
repo_name: ambitiousconcepts/TaxDocs
edit_uri: edit/main/docs/

# GitHub Pages Configuration
site_url: https://ambitiousconcepts.github.io/TaxDocs/
strict: true

# Theme configuration
theme:
  name: material  # Material for MkDocs theme (highly recommended)
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

# Navigation structure
nav:
  - Home: index.md
  - Getting Started: 
    # - Installation: getting-started/installation.md
    # - Quick Start: getting-started/quick-start.md
    - Features: getting-started/features.md
    - Tech Stack: getting-started/tech-stack.md
    - Development Timeline: getting-started/development-timeline.md
    - Payment Structure: getting-started/payment-structure.md
  # - User Guide:
  #   - Overview: user-guide/overview.md
  #   - Features: user-guide/features.md
  #   - Configuration: user-guide/configuration.md
  # - API Reference: api-reference.md
  # - FAQ: faq.md
  # - Contributing: contributing.md

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list

# Plugins
plugins:
  - search
  - minify